name: Terraform CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Terraform

    steps:
     
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::010438485124:role/github-actions-role  
          aws-region: eu-west-2

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan
      
      - name: Deploy website to S3
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        working-directory: .
        run: aws s3 sync Resume/ s3://kanems97-website-bucket --delete

      